name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SSH
          run: rustup update stable && rustup default stable
          run: cargo build --release
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_ed25519
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
            ssh-keyscan -H tncars.pp.ua > ~/.ssh/known_hosts
          run: scp target/release/bible-api berinaniesh@tncars.pp.ua:/home/berinaniesh/tmp/bible-api
