name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout and toolchain
        run: rustup update stable && rustup default stable
      - name: Test
        run: cargo test
      - name: Build
        run: cargo build --release
      - name: SSH setup
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          ssh-keyscan -H versequick.com > ~/.ssh/known_hosts
      - name: Deploy
        run: scp target/release/versequick-api berinaniesh@versequick.com:/home/berinaniesh/tmp/versequick-api
